title: Kyson
description: Aspiring Secuirty Researcher
url: "https://ky-son.github.io"
baseurl: ""

permalink: /:categories/:title/

collections_dir: .

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
